apiVersion: apps/v1
kind: Deployment
metadata:
  name: recognizer-layout
  labels:
    app: recognizer-layout-deployment
spec:
  selector:
    matchLabels:
      app: recognizer-layout-app
  replicas: 1
  template:
    metadata:
      labels:
        app: recognizer-layout-app
    spec:
      containers:
      - name: azure-cognitive-service-layout
        image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/layout
        ports:
        - containerPort: 5000
        env:
        - name: EULA
          value: accept
        - name: billing
          value: {FR_ENDPOINT}
        - name: apikey
          value: {FR_KEY}
        - name: AzureCognitiveServiceReadHost
          value: http://azure-cognitive-service-read:5000
        resources:
          limits:
            sgx.intel.com/epc: 5Mi # This limit will automatically place the job into a confidential computing node and mount the required driver volumes. Alternatively, you can target deployment to node pools with node selector.
        livenessProbe:
          httpGet:
            path: /ContainerLiveness
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 20
--- 
apiVersion: v1
kind: Service
metadata:
  name: recognizer-layout
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: recognizer-layout-app